const AUTH = {
    REGISTER_USER_IN_PROGRESS: 'REGISTER_USER_IN_PROGRESS',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_ERROR: 'REGISTER_USER_ERROR',
    RETRIEVE_USER_FROM_LOCAL: 'RETRIEVE_USER_FROM_LOCAL',
    REMOVE_USERINFO: 'REMOVE_USERINFO'
}

export default AUTH;